-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 21:02:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ngolo_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ngolo_db` ;

-- -----------------------------------------------------
-- Schema ngolo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ngolo_db` DEFAULT CHARACTER SET utf8 ;
USE `ngolo_db` ;

-- -----------------------------------------------------
-- Table `ngolo_db`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngolo_db`.`profiles` ;

CREATE TABLE IF NOT EXISTS `ngolo_db`.`profiles` (
  `profileID` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`profileID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngolo_db`.`utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngolo_db`.`utilisateurs` ;

CREATE TABLE IF NOT EXISTS `ngolo_db`.`utilisateurs` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `profileID` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `profileID_users_idx` (`profileID` ASC),
  CONSTRAINT `profileID_users`
    FOREIGN KEY (`profileID`)
    REFERENCES `ngolo_db`.`profiles` (`profileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ngolo_db`.`profiles`
-- -----------------------------------------------------
START TRANSACTION;
USE `ngolo_db`;
INSERT INTO `ngolo_db`.`profiles` (`profileID`, `name`) VALUES (1, 'ADMIN');
INSERT INTO `ngolo_db`.`profiles` (`profileID`, `name`) VALUES (2, 'CLIENT');

COMMIT;

